INFO - 2023-09-09 03:33:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 03:33:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 03:33:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 03:33:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 03:35:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 03:53:25 --> Class "App\Modules\Admin\Models\UserModel" not found
in APPPATH\Modules\Admin\Controllers\Dashboard.php on line 20.
 1 SYSTEMPATH\CodeIgniter.php(887): App\Modules\Admin\Controllers\Dashboard->__construct()
 2 SYSTEMPATH\CodeIgniter.php(483): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 03:53:25 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "App\Modules\Admin\Models\UserModel" not found
#0 C:\wamp64\www\modelo\system\CodeIgniter.php(887): App\Modules\Admin\Controllers\Dashboard->__construct()
#1 C:\wamp64\www\modelo\system\CodeIgniter.php(483): CodeIgniter\CodeIgniter->createController()
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#4 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-09-09 03:53:37 --> Class "App\Modules\Admin\Models\UserModel" not found
in APPPATH\Modules\Admin\Controllers\Dashboard.php on line 20.
 1 SYSTEMPATH\CodeIgniter.php(887): App\Modules\Admin\Controllers\Dashboard->__construct()
 2 SYSTEMPATH\CodeIgniter.php(483): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 03:53:37 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "App\Modules\Admin\Models\UserModel" not found
#0 C:\wamp64\www\modelo\system\CodeIgniter.php(887): App\Modules\Admin\Controllers\Dashboard->__construct()
#1 C:\wamp64\www\modelo\system\CodeIgniter.php(483): CodeIgniter\CodeIgniter->createController()
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#4 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-09-09 03:53:53 --> Class "App\Modules\Admin\Models\UserModel" not found
in APPPATH\Modules\Admin\Controllers\Dashboard.php on line 20.
 1 SYSTEMPATH\CodeIgniter.php(887): App\Modules\Admin\Controllers\Dashboard->__construct()
 2 SYSTEMPATH\CodeIgniter.php(483): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 03:53:53 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "App\Modules\Admin\Models\UserModel" not found
#0 C:\wamp64\www\modelo\system\CodeIgniter.php(887): App\Modules\Admin\Controllers\Dashboard->__construct()
#1 C:\wamp64\www\modelo\system\CodeIgniter.php(483): CodeIgniter\CodeIgniter->createController()
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#4 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 03:57:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 03:57:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 03:57:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 03:57:45 --> Undefined property: stdClass::$id
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$id', 'C:\\wamp64\\www\\modelo\\app\\Modules\\Admin\\Models\\LoginModel.php', 30)
 2 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 3 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 4 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 03:57:45 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ErrorException), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(ErrorException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
【Previous Exception】
ErrorException
Undefined property: stdClass::$id
#0 C:\wamp64\www\modelo\app\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\wamp64\\www\\m...', 30)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#6 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 03:57:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 03:58:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 03:58:02 --> Attempt to read property "id" on null
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "id" on null', 'C:\\wamp64\\www\\modelo\\app\\Modules\\Admin\\Models\\LoginModel.php', 30)
 2 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('josue', 'josue')
 3 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 4 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 03:58:02 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ErrorException), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(ErrorException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
【Previous Exception】
ErrorException
Attempt to read property "id" on null
#0 C:\wamp64\www\modelo\app\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\wamp64\\www\\m...', 30)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('josue', 'josue')
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#6 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:10:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:10:18 --> Attempt to read property "id" on null
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "id" on null', 'C:\\wamp64\\www\\modelo\\app\\Modules\\Admin\\Models\\LoginModel.php', 30)
 2 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('josue', 'josue')
 3 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 4 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:10:18 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ErrorException), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(ErrorException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
【Previous Exception】
ErrorException
Attempt to read property "id" on null
#0 C:\wamp64\www\modelo\app\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\wamp64\\www\\m...', 30)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('josue', 'josue')
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#6 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:18:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:18:18 --> Attempt to read property "id" on null
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "id" on null', 'C:\\wamp64\\www\\modelo\\app\\Modules\\Admin\\Models\\LoginModel.php', 30)
 2 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('josue', 'josue')
 3 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 4 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:18:18 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ErrorException), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(ErrorException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
【Previous Exception】
ErrorException
Attempt to read property "id" on null
#0 C:\wamp64\www\modelo\app\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\wamp64\\www\\m...', 30)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('josue', 'josue')
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#6 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:18:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:18:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:18:32 --> Undefined property: stdClass::$id
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$id', 'C:\\wamp64\\www\\modelo\\app\\Modules\\Admin\\Models\\LoginModel.php', 30)
 2 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 3 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 4 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:18:32 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ErrorException), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(ErrorException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
【Previous Exception】
ErrorException
Undefined property: stdClass::$id
#0 C:\wamp64\www\modelo\app\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\wamp64\\www\\m...', 30)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#6 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:19:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:19:59 --> Undefined property: stdClass::$id
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$id', 'C:\\wamp64\\www\\modelo\\app\\Modules\\Admin\\Models\\LoginModel.php', 30)
 2 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 3 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 4 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:19:59 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ErrorException), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(ErrorException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
【Previous Exception】
ErrorException
Undefined property: stdClass::$id
#0 C:\wamp64\www\modelo\app\Modules\Admin\Models\LoginModel.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\wamp64\\www\\m...', 30)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#6 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:24:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:24:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:26:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:26:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:26:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:36:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:36:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:36:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:36:23 --> Call to undefined function App\Modules\Admin\Models\now()
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 2 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 3 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:36:23 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Call to undefined function App\Modules\Admin\Models\now()
#0 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#1 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#5 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:37:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:37:21 --> Call to undefined function App\Modules\Admin\Models\NOW()
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 2 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 3 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:37:21 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Call to undefined function App\Modules\Admin\Models\NOW()
#0 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#1 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#5 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:37:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:37:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:37:36 --> Call to undefined function App\Modules\Admin\Models\NOW()
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 2 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 3 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:37:36 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Call to undefined function App\Modules\Admin\Models\NOW()
#0 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#1 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#5 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:38:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:38:19 --> Call to undefined function App\Modules\Admin\Models\now()
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 2 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 3 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:38:19 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Call to undefined function App\Modules\Admin\Models\now()
#0 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#1 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#5 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:38:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:38:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:38:37 --> Call to undefined function App\Modules\Admin\Models\now()
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 2 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 3 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:38:37 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Call to undefined function App\Modules\Admin\Models\now()
#0 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#1 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#5 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:39:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:39:50 --> Class "App\Modules\Admin\Models\Time" not found
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 2 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 3 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:39:50 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "App\Modules\Admin\Models\Time" not found
#0 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#1 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#5 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:40:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:40:58 --> Class "App\Modules\Admin\Models\Time" not found
in APPPATH\Modules\Admin\Models\LoginModel.php on line 30.
 1 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 2 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 3 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:40:58 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#5 {main}
  thrown
【Previous Exception】
Error
Class "App\Modules\Admin\Models\Time" not found
#0 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#1 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#5 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:41:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:41:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:58:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:58:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:58:40 --> Attempt to read property "user_id" on null
in APPPATH\Modules\Admin\Models\LoginModel.php on line 32.
 1 APPPATH\Modules\Admin\Models\LoginModel.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_id" on null', 'C:\\wamp64\\www\\modelo\\app\\Modules\\Admin\\Models\\LoginModel.php', 32)
 2 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 3 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 4 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:58:40 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ErrorException), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(ErrorException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
【Previous Exception】
ErrorException
Attempt to read property "user_id" on null
#0 C:\wamp64\www\modelo\app\Modules\Admin\Models\LoginModel.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\wamp64\\www\\m...', 32)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#6 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:59:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:59:15 --> Attempt to read property "login_id" on null
in APPPATH\Modules\Admin\Models\LoginModel.php on line 32.
 1 APPPATH\Modules\Admin\Models\LoginModel.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "login_id" on null', 'C:\\wamp64\\www\\modelo\\app\\Modules\\Admin\\Models\\LoginModel.php', 32)
 2 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 3 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 4 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:59:15 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ErrorException), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(ErrorException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
【Previous Exception】
ErrorException
Attempt to read property "login_id" on null
#0 C:\wamp64\www\modelo\app\Modules\Admin\Models\LoginModel.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\wamp64\\www\\m...', 32)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#6 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:59:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:59:33 --> Attempt to read property "login_id" on null
in APPPATH\Modules\Admin\Models\LoginModel.php on line 32.
 1 APPPATH\Modules\Admin\Models\LoginModel.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "login_id" on null', 'C:\\wamp64\\www\\modelo\\app\\Modules\\Admin\\Models\\LoginModel.php', 32)
 2 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 3 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 4 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:59:33 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ErrorException), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(ErrorException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
【Previous Exception】
ErrorException
Attempt to read property "login_id" on null
#0 C:\wamp64\www\modelo\app\Modules\Admin\Models\LoginModel.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\wamp64\\www\\m...', 32)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#6 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 04:59:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 04:59:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
CRITICAL - 2023-09-09 04:59:45 --> Attempt to read property "login_id" on null
in APPPATH\Modules\Admin\Models\LoginModel.php on line 32.
 1 APPPATH\Modules\Admin\Models\LoginModel.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "login_id" on null', 'C:\\wamp64\\www\\modelo\\app\\Modules\\Admin\\Models\\LoginModel.php', 32)
 2 APPPATH\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
 3 SYSTEMPATH\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
 4 SYSTEMPATH\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-09 04:59:45 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in C:\wamp64\www\modelo\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(241): include()
#1 C:\wamp64\www\modelo\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 C:\wamp64\www\modelo\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(ErrorException), 500, 'C:\\wamp64\\www\\m...')
#3 C:\wamp64\www\modelo\system\Debug\Exceptions.php(147): CodeIgniter\Debug\ExceptionHandler->handle(Object(ErrorException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
【Previous Exception】
ErrorException
Attempt to read property "login_id" on null
#0 C:\wamp64\www\modelo\app\Modules\Admin\Models\LoginModel.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\wamp64\\www\\m...', 32)
#1 C:\wamp64\www\modelo\app\Modules\Admin\Controllers\Dashboard.php(43): App\Modules\Admin\Models\LoginModel->login('admin', 'admin123')
#2 C:\wamp64\www\modelo\system\CodeIgniter.php(915): App\Modules\Admin\Controllers\Dashboard->login()
#3 C:\wamp64\www\modelo\system\CodeIgniter.php(492): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Admin\Controllers\Dashboard))
#4 C:\wamp64\www\modelo\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\wamp64\www\modelo\index.php(79): CodeIgniter\CodeIgniter->run()
#6 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-09-09 05:01:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 05:01:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
INFO - 2023-09-09 05:01:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\DatabaseHandler' driver.
